### ISSUE TITLE
Correct way to upgrade?

### ISSUE THREAD

**Issue by dmd** [mercure-imaging/mercure#37]
What is the correct way to upgrade to the latest mercure, in docker mode?

For example, simply doing a git checkout to change branch to the latest version and rerunning install.sh does _not_ work - it doesn't update docker-compose.yaml.

**Comment by dmd** [comment]
I guess this project is dead [again]?

**Comment by tblock79** [comment]
This project is not dead. Keep in mind that we are developing it as one of several open-source projects without receiving compensation. Therefore, we have very limited time for providing support to external users, especially on docker-specific aspects.

Questions regarding usage of the software should be posted to the Discussion Board, so that other community members can respond.

**Comment by dmd** [comment]
We do thank you VERY much for this project. And if there were a way to pay for it - some kind of monthly or yearly support fee - we would be overjoyed to pay it!

**Comment by RoyWiggins** [comment]
You're correct, there isn't really an official upgrade process documented it's probably time to fix this, though of course it's always harder to reliably upgrade something than to start from scratch. 

Upgrading the docker-compose installation used to be a matter of shutting the service down, copying the new `docker-compose.yml` over the old one, and starting it again, but the install script now generates a `docker-compose` file somewhat programmatically. Perhaps we could add a mode to the installer to rebuild the docker-compose file... that might work well enough, but it would discard any intentional customizations made to the docker-compose file, so maybe not ideal. 

To do it manually you can open the `/opt/mercure/docker-compose.yml` and switch the version tags on all the images to the latest release (`0.2.2-alpha.2`) and then `docker-compose down` and `docker-compose up` to recreate the containers with the new image. That *should* work.

**Comment by dmd** [comment]
Is there configuration anywhere other than in `/opt/mercure/config`? Could I just preserve that directory, and wipe everything out and start from scratch and then restore that directory?

**Comment by RoyWiggins** [comment]
Now I think about it again, it should be sufficient to just delete `/opt/mercure/docker-compose.yml` and re-run install.sh. It will write the new version of the docker-compose file out and then you can bring the service back up.
