### ISSUE TITLE
send.py dcmsend arguments extension

### ISSUE THREAD

**Issue by alipairon** [mercure-imaging/mercure#48]
Hello!

I would like to suggest adding as an option the "-dn" flag for dcmsend command in send.py

It's useful when SCP accepts the compressed and uncompressed syntaxes at the same time (and most of them are), the dcmsend without this flag will prefer the uncompressed one and will decompress it before sending it to SCP.

**Comment by tblock79** [comment]
The -dn flag forces dcmsend to never decompress the images. This would break compliance with the DICOM standard because according to the DICOM standard, every DICOM node must be able to provide images also in decompressed format. Otherwise, the connection would fail if the receiver/target is unable to handle compressed images. Therefore, setting the -dn flag would not be a good idea. 

We can take a look at whether dcmsend could be replaced with storescu, which offers more flexibility for configuring the proposed transfer syntax.
