### ISSUE TITLE
Receiver reset problem

### ISSUE THREAD

**Issue by faaronts** [mercure-imaging/mercure#58]
**Describe the bug**

When several DICOMs are sent to mercure from an external machine (not within the VM) using the `dcmsend` command, the receiver is reset with the following error in the Receiver Logs: 

`Oct 14 16:45:32 vagrant receiver.sh[13431]: E: 0006:031d TCP I/O Error (Connection reset by peer) occurred in routine: sendAssociationACTCP
`

Moreover, if I attemp to send a new case after the reset, the `dcmsend` command execution time will last almost 1 minute due to `Requesting association` lasting almost a minute. 

This behaviour is not seen everytime a file is sent from an external machine, but after several succesfull `dcmsend` executions. After that, every `dcmsend` will last almost a minute, compared to only msec in a normal situation. 

Also, if I repeat these repetitive `dcmsend` commands on the mercure's VM, all of them execute as expected at any moment.

**Comment by tblock79** [comment]
This error message is created by the storescp tool from the DCMTK package. mercure is using the storescp tool to receive DICOM series. Therefore, this issue is out of mercure's scope. You could check with the OFFIS DCMTK team regarding the error message. The storescp tool is widely used and pretty stable, so I assume that it might have to do with your VM setup (maybe a firewall or CPU load issue that intercepts the connection). For production use, mercure should not be installed in a VM (the Vagrant setup is only intended for testing and development work).
