### ISSUE TITLE
Systemd Install creates a docker network interface

### ISSUE THREAD

**Issue by cadrogui** [mercure-imaging/mercure#77]
**Describe the bug**

When performs a systemd installation, the script create a new docker network iface named docker0, in my case with 172.0.0.7/16 CIDR, and the new iface 172.18.0.0/16, so  i can reach traffic in the 172.18.0.0 segments in my network.

**To Reproduce**

follow the standard installation for systemd:

![image](https://github.com/mercure-imaging/mercure/assets/5303414/20070cd5-7fcc-4af0-96ff-ea357da2c8b5)

**Expected behavior**

i understand if i dont select docker installation the systemd scirpt doesnt have to créate a docker network interfaces.

**Comment by tblock79** [comment]
Even when using a systemd installation, mercure needs access to Docker because the processing modules are Docker containers.  mercure must be able to pull, start, and stop those container images. Therefore, the latest Docker version gets installed during the mercure installation. If you are not planning to use any processing steps, you can probably comment-out the Docker installation function in the installation script, but by default Docker should be installed with mercure.

**Comment by cadrogui** [comment]
Hi, thanks for your answer, Ive got a better solution, i`ll send pr.

Regards.

**Comment by guruevi** [comment]
There are plenty of resources online on how to change the default Docker network:
https://support.hyperglance.com/knowledge/changing-the-default-docker-subnet
